'use client';

import { BookOpen, Sparkles, Upload, PenLine, Film } from 'lucide-react';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import type { ProjectOverview, StorylineSource } from '@/lib/types';

const STORYLINE_SOURCE_LABELS: Record<StorylineSource, string> = {
  MUSE_GENERATED: 'Generated by Story Muse',
  UPLOAD: 'Uploaded document',
  MANUAL: 'Written manually',
};

export interface ProjectOverviewSheetProps {
  project: ProjectOverview;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function ProjectOverviewSheet({ project, open, onOpenChange }: ProjectOverviewSheetProps) {
  const { title, description, storyline, storylineSource, scenes } = project;
  const SourceIcon =
    storylineSource === 'MUSE_GENERATED'
      ? Sparkles
      : storylineSource === 'UPLOAD'
        ? Upload
        : PenLine;

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent
        side="right"
        className="w-[420px] max-w-[95vw] border-white/8 bg-[oklch(0.13_0.012_264)] p-0 flex flex-col"
      >
        <SheetHeader className="border-b border-white/8 px-5 py-4 shrink-0">
          <SheetTitle className="flex items-center gap-2 text-sm font-semibold pr-8">
            <BookOpen className="h-4 w-4 text-violet-400" />
            Project overview
          </SheetTitle>
          <SheetDescription className="text-xs text-muted-foreground">
            A quick reminder of this project's storyline and script.
          </SheetDescription>
        </SheetHeader>

        <div className="flex flex-1 flex-col gap-6 overflow-y-auto p-5">
          {/* Title & description */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5">
              Project
            </h3>
            <p className="font-medium text-foreground">{title}</p>
            {description && (
              <p className="mt-1 text-sm text-muted-foreground leading-relaxed">{description}</p>
            )}
          </section>

          {/* Storyline source */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5">
              Storyline source
            </h3>
            <div className="flex items-center gap-2 rounded-lg border border-white/8 bg-white/5 px-3 py-2">
              <SourceIcon className="h-4 w-4 text-violet-400 shrink-0" />
              <span className="text-sm text-foreground/90">
                {STORYLINE_SOURCE_LABELS[storylineSource]}
              </span>
            </div>
          </section>

          {/* Storyline content */}
          {storyline && (
            <section>
              <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5">
                Storyline
              </h3>
              <div className="rounded-xl border border-white/8 bg-white/5 p-4 space-y-3 text-sm">
                {storyline.logline && (
                  <div>
                    <p className="text-[10px] font-semibold text-muted-foreground uppercase mb-0.5">
                      Logline
                    </p>
                    <p className="text-foreground/90 leading-relaxed">{storyline.logline}</p>
                  </div>
                )}
                <div>
                  <p className="text-[10px] font-semibold text-muted-foreground uppercase mb-0.5">
                    Plot outline
                  </p>
                  <p className="text-foreground/90 leading-relaxed whitespace-pre-wrap">
                    {storyline.plotOutline}
                  </p>
                </div>
                {storyline.genre && (
                  <div>
                    <p className="text-[10px] font-semibold text-muted-foreground uppercase mb-0.5">
                      Genre
                    </p>
                    <p className="text-foreground/90">{storyline.genre}</p>
                  </div>
                )}
                {storyline.characters?.length > 0 && (
                  <div>
                    <p className="text-[10px] font-semibold text-muted-foreground uppercase mb-0.5">
                      Characters
                    </p>
                    <ul className="list-disc list-inside text-foreground/90 space-y-0.5">
                      {storyline.characters.map((c, i) => (
                        <li key={i}>{c}</li>
                      ))}
                    </ul>
                  </div>
                )}
                {storyline.themes?.length > 0 && (
                  <div>
                    <p className="text-[10px] font-semibold text-muted-foreground uppercase mb-0.5">
                      Themes
                    </p>
                    <p className="text-foreground/90">{storyline.themes.join(', ')}</p>
                  </div>
                )}
              </div>
            </section>
          )}

          {/* Scenes (script) */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
              <Film className="h-3.5 w-3.5" />
              Scenes
            </h3>
            {scenes.length === 0 ? (
              <p className="text-sm text-muted-foreground rounded-lg border border-white/8 bg-white/5 px-3 py-4">
                No scenes yet.
              </p>
            ) : (
              <div className="space-y-2">
                {scenes
                  .slice()
                  .sort((a, b) => a.sceneNumber - b.sceneNumber)
                  .map((scene) => (
                    <div
                      key={scene.id}
                      className="rounded-lg border border-white/8 bg-white/5 p-3 text-sm"
                    >
                      <p className="font-medium text-foreground">
                        {scene.sceneNumber}. {scene.title || scene.heading || 'Untitled'}
                      </p>
                      {scene.heading && scene.heading !== scene.title && (
                        <p className="text-xs text-muted-foreground mt-0.5">{scene.heading}</p>
                      )}
                      {scene.description && (
                        <p className="text-muted-foreground mt-1 leading-relaxed line-clamp-3">
                          {scene.description}
                        </p>
                      )}
                    </div>
                  ))}
              </div>
            )}
          </section>
        </div>
      </SheetContent>
    </Sheet>
  );
}
